
#region License

// Copyright (c) 2013, ClearCanvas Inc.
// All rights reserved.
// http://www.clearcanvas.ca
//
// This file is part of the ClearCanvas RIS/PACS open source project.
//
// The ClearCanvas RIS/PACS open source project is free software: you can
// redistribute it and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The ClearCanvas RIS/PACS open source project is distributed in the hope that it
// will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// the ClearCanvas RIS/PACS open source project.  If not, see
// <http://www.gnu.org/licenses/>.

#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.Common {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class MemoryManagementSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MemoryManagementSettings defaultInstance = ((MemoryManagementSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MemoryManagementSettings())));
        
        public static MemoryManagementSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// The high watermark for process virtual memory.  When the high watermark is hit, memory management will unload objects until it reaches the low watermark.  A value of -1 means this value is computed automatically.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The high watermark for process virtual memory.  When the high watermark is hit, m" +
            "emory management will unload objects until it reaches the low watermark.  A valu" +
            "e of -1 means this value is computed automatically.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public long HighWatermarkMegaBytes {
            get {
                return ((long)(this["HighWatermarkMegaBytes"]));
            }
        }
        
        /// <summary>
        /// The low watermark for process virtual memory.  When the high watermark is hit, memory management will unload objects until it reaches the low watermark.  A value of -1 means this value is computed automatically.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The low watermark for process virtual memory.  When the high watermark is hit, me" +
            "mory management will unload objects until it reaches the low watermark.  A value" +
            " of -1 means this value is computed automatically.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public long LowWatermarkMegaBytes {
            get {
                return ((long)(this["LowWatermarkMegaBytes"]));
            }
        }
    }
}
