
#region License

// Copyright (c) 2013, ClearCanvas Inc.
// All rights reserved.
// http://www.clearcanvas.ca
//
// This file is part of the ClearCanvas RIS/PACS open source project.
//
// The ClearCanvas RIS/PACS open source project is free software: you can
// redistribute it and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The ClearCanvas RIS/PACS open source project is distributed in the hope that it
// will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// the ClearCanvas RIS/PACS open source project.  If not, see
// <http://www.gnu.org/licenses/>.

#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.StudyLoaders.Streaming.WebStation {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class WebStationStreamingSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static WebStationStreamingSettings defaultInstance = ((WebStationStreamingSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WebStationStreamingSettings())));
        
        public static WebStationStreamingSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Format of a WADO URL (2 items, server and port).
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Format of a WADO URL (2 items, server and port).")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://{0}:{1}/WADO")]
        public string FormatWadoUriPrefix {
            get {
                return ((string)(this["FormatWadoUriPrefix"]));
            }
        }
        
        /// <summary>
        /// Format of a header streaming service URL.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Format of a header streaming service URL.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://{0}:{1}/HeaderStreaming/HeaderStreaming")]
        public string FormatHeaderServiceUri {
            get {
                return ((string)(this["FormatHeaderServiceUri"]));
            }
        }
        
        /// <summary>
        /// The number of concurrent threads that should be used to pre-fetch streamed image data.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The number of concurrent threads that should be used to pre-fetch streamed image " +
            "data.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int RetrieveConcurrency {
            get {
                return ((int)(this["RetrieveConcurrency"]));
            }
        }
        
        /// <summary>
        /// An arbitrary weighting value for loading images in the selected image box versus all the other unselected image boxes.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("An arbitrary weighting value for loading images in the selected image box versus " +
            "all the other unselected image boxes.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SelectedWeighting {
            get {
                return ((int)(this["SelectedWeighting"]));
            }
        }
        
        /// <summary>
        /// An arbitrary weighting value for loading images in the selected image box versus all the other unselected image boxes.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("An arbitrary weighting value for loading images in the selected image box versus " +
            "all the other unselected image boxes.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int UnselectedWeighting {
            get {
                return ((int)(this["UnselectedWeighting"]));
            }
        }
        
        /// <summary>
        /// The number of concurrent threads used to decompress pre-fetched image pixel data.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The number of concurrent threads used to decompress pre-fetched image pixel data." +
            "")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DecompressConcurrency {
            get {
                return ((int)(this["DecompressConcurrency"]));
            }
        }
        
        /// <summary>
        /// The number of images ahead and behind the current (visible) image to pre-fetch the pixel data for.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The number of images ahead and behind the current (visible) image to pre-fetch th" +
            "e pixel data for.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ImageWindow {
            get {
                return ((int)(this["ImageWindow"]));
            }
        }
        
        /// <summary>
        /// The minimum amount of available memory required for pre-fetching to continue.  If this limit is hit, pre-fetching stops for the remainder of the viewer session.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The minimum amount of available memory required for pre-fetching to continue.  If" +
            " this limit is hit, pre-fetching stops for the remainder of the viewer session.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int AvailableMemoryLimitMegabytes {
            get {
                return ((int)(this["AvailableMemoryLimitMegabytes"]));
            }
        }
    }
}
