
#region License

// Copyright (c) 2013, ClearCanvas Inc.
// All rights reserved.
// http://www.clearcanvas.ca
//
// This file is part of the ClearCanvas RIS/PACS open source project.
//
// The ClearCanvas RIS/PACS open source project is free software: you can
// redistribute it and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The ClearCanvas RIS/PACS open source project is distributed in the hope that it
// will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// the ClearCanvas RIS/PACS open source project.  If not, see
// <http://www.gnu.org/licenses/>.

#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.StudyManagement {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macro.ImageViewer.StudyManagement.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 任务 的本地化字符串。
        /// </summary>
        public static string ColumnActivityDescription {
            get {
                return ResourceManager.GetString("ColumnActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病人 的本地化字符串。
        /// </summary>
        public static string ColumnPatient {
            get {
                return ResourceManager.GetString("ColumnPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先级 的本地化字符串。
        /// </summary>
        public static string ColumnPriority {
            get {
                return ResourceManager.GetString("ColumnPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度 的本地化字符串。
        /// </summary>
        public static string ColumnProgress {
            get {
                return ResourceManager.GetString("ColumnProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求时间 的本地化字符串。
        /// </summary>
        public static string ColumnRequestedTime {
            get {
                return ResourceManager.GetString("ColumnRequestedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行时间 的本地化字符串。
        /// </summary>
        public static string ColumnScheduledTime {
            get {
                return ResourceManager.GetString("ColumnScheduledTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string ColumnStatus {
            get {
                return ResourceManager.GetString("ColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态信息 的本地化字符串。
        /// </summary>
        public static string ColumnStatusDescription {
            get {
                return ResourceManager.GetString("ColumnStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查 的本地化字符串。
        /// </summary>
        public static string ColumnStudy {
            get {
                return ResourceManager.GetString("ColumnStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁盘空间已满 的本地化字符串。
        /// </summary>
        public static string DescriptionMaximumDiskUsageExceeded {
            get {
                return ResourceManager.GetString("DescriptionMaximumDiskUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} of {1} ({2}%) 的本地化字符串。
        /// </summary>
        public static string DiskspaceTemplate {
            get {
                return ResourceManager.GetString("DiskspaceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务监视器 的本地化字符串。
        /// </summary>
        public static string LinkOpenActivityMonitor {
            get {
                return ResourceManager.GetString("LinkOpenActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储配置 的本地化字符串。
        /// </summary>
        public static string LinkOpenStorageConfiguration {
            get {
                return ResourceManager.GetString("LinkOpenStorageConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器工作列表 的本地化字符串。
        /// </summary>
        public static string MenuActivityMonitor {
            get {
                return ResourceManager.GetString("MenuActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string MenuDeleteWorkItem {
            get {
                return ResourceManager.GetString("MenuDeleteWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库维护 的本地化字符串。
        /// </summary>
        public static string MenuReindex {
            get {
                return ResourceManager.GetString("MenuReindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新启动 的本地化字符串。
        /// </summary>
        public static string MenuRestartWorkItem {
            get {
                return ResourceManager.GetString("MenuRestartWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make Stat 的本地化字符串。
        /// </summary>
        public static string MenuStatWorkItem {
            get {
                return ResourceManager.GetString("MenuStatWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string MenuStopWorkItem {
            get {
                return ResourceManager.GetString("MenuStopWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定取消？ 的本地化字符串。
        /// </summary>
        public static string MessageConfirmCancelWorkItems {
            get {
                return ResourceManager.GetString("MessageConfirmCancelWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开图像失败 的本地化字符串。
        /// </summary>
        public static string MessageFailedToOpenImages {
            get {
                return ResourceManager.GetString("MessageFailedToOpenImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开检查失败 的本地化字符串。
        /// </summary>
        public static string MessageFailedToOpenStudy {
            get {
                return ResourceManager.GetString("MessageFailedToOpenStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重建图像索引失败 的本地化字符串。
        /// </summary>
        public static string MessageFailedToStartReindex {
            get {
                return ResourceManager.GetString("MessageFailedToStartReindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储图像目录不存在 的本地化字符串。
        /// </summary>
        public static string MessageFilestoreDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("MessageFilestoreDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此检查正在处理中，是否要进行此操作？ 的本地化字符串。
        /// </summary>
        public static string MessageLoadStudiesBeingProcessed {
            get {
                return ResourceManager.GetString("MessageLoadStudiesBeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此检查正在处理中，是否要进行此操作？ 的本地化字符串。
        /// </summary>
        public static string MessageLoadStudyBeingProcessed {
            get {
                return ResourceManager.GetString("MessageLoadStudyBeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地服务器没有启动 的本地化字符串。
        /// </summary>
        public static string MessageLocalServerNotRunning {
            get {
                return ResourceManager.GetString("MessageLocalServerNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁盘已满 的本地化字符串。
        /// </summary>
        public static string MessageMaximumDiskUsageExceeded {
            get {
                return ResourceManager.GetString("MessageMaximumDiskUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 失败. 的本地化字符串。
        /// </summary>
        public static string MessageNonStudyWorkItemFailed {
            get {
                return ResourceManager.GetString("MessageNonStudyWorkItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 工作项失败. 的本地化字符串。
        /// </summary>
        public static string MessageOneFailedWorkItem {
            get {
                return ResourceManager.GetString("MessageOneFailedWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processed {0} of {1} items... 的本地化字符串。
        /// </summary>
        public static string MessageProcessedItemsProgress {
            get {
                return ResourceManager.GetString("MessageProcessedItemsProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在建立图像索引 的本地化字符串。
        /// </summary>
        public static string MessageReindexInProgress {
            get {
                return ResourceManager.GetString("MessageReindexInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行建立图像索引 的本地化字符串。
        /// </summary>
        public static string MessageReindexScheduled {
            get {
                return ResourceManager.GetString("MessageReindexScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地服务器没有启动 的本地化字符串。
        /// </summary>
        public static string MessageReindexServiceNotRunning {
            get {
                return ResourceManager.GetString("MessageReindexServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  {0} 工作项失败. 的本地化字符串。
        /// </summary>
        public static string MessageTotalFailedWorkItems {
            get {
                return ResourceManager.GetString("MessageTotalFailedWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} for {1} [{2}, A#:{3}] 失败. 的本地化字符串。
        /// </summary>
        public static string MessageWorkItemFailed {
            get {
                return ResourceManager.GetString("MessageWorkItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (all) 的本地化字符串。
        /// </summary>
        public static string NoFilterItem {
            get {
                return ResourceManager.GetString("NoFilterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在进行中 的本地化字符串。
        /// </summary>
        public static string StatusFilterValueActive {
            get {
                return ResourceManager.GetString("StatusFilterValueActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string StatusFilterValueComplete {
            get {
                return ResourceManager.GetString("StatusFilterValueComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public static string StatusFilterValueFailed {
            get {
                return ResourceManager.GetString("StatusFilterValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string StatusFilterValueStopped {
            get {
                return ResourceManager.GetString("StatusFilterValueStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器工作列表 的本地化字符串。
        /// </summary>
        public static string TitleActivityMonitor {
            get {
                return ResourceManager.GetString("TitleActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器工作列表 的本地化字符串。
        /// </summary>
        public static string TooltipActivityMonitor {
            get {
                return ResourceManager.GetString("TooltipActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string TooltipDeleteWorkItem {
            get {
                return ResourceManager.GetString("TooltipDeleteWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启 的本地化字符串。
        /// </summary>
        public static string TooltipRestartWorkItem {
            get {
                return ResourceManager.GetString("TooltipRestartWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提升优先级 的本地化字符串。
        /// </summary>
        public static string TooltipStatWorkItem {
            get {
                return ResourceManager.GetString("TooltipStatWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string TooltipStopWorkItem {
            get {
                return ResourceManager.GetString("TooltipStopWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无权打开监视器 的本地化字符串。
        /// </summary>
        public static string WarningActivityMonitorPermission {
            get {
                return ResourceManager.GetString("WarningActivityMonitorPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁盘已满 的本地化字符串。
        /// </summary>
        public static string WarningMaximumDiskUsageExceeded {
            get {
                return ResourceManager.GetString("WarningMaximumDiskUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无权执行建立图像索引 的本地化字符串。
        /// </summary>
        public static string WarningReindexPermission {
            get {
                return ResourceManager.GetString("WarningReindexPermission", resourceCulture);
            }
        }
    }
}
