
#region License

// Copyright (c) 2013, ClearCanvas Inc.
// All rights reserved.
// http://www.clearcanvas.ca
//
// This file is part of the ClearCanvas RIS/PACS open source project.
//
// The ClearCanvas RIS/PACS open source project is free software: you can
// redistribute it and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The ClearCanvas RIS/PACS open source project is distributed in the hope that it
// will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// the ClearCanvas RIS/PACS open source project.  If not, see
// <http://www.gnu.org/licenses/>.

#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.Common {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ProductSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProductSettings defaultInstance = ((ProductSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProductSettings())));
        
        public static ProductSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// The product name.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The product name.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+nH5OL3K6/xP46EmaJ4HWw==")]
        public string Component {
            get {
                return ((string)(this["Component"]));
            }
        }
        
        /// <summary>
        /// The version of the product, which can be different from that of the assemblies.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The version of the product, which can be different from that of the assemblies.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("q+MreiMibM0=")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
        }
        
        /// <summary>
        /// Product version suffix (e.g. SP1).
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Product version suffix (e.g. SP1).")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mTaoDcie2GM=")]
        public string VersionSuffix {
            get {
                return ((string)(this["VersionSuffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+nH5OL3K6/xP46EmaJ4HWw==")]
        public string Product {
            get {
                return ((string)(this["Product"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("q+MreiMibM0=")]
        public string Edition {
            get {
                return ((string)(this["Edition"]));
            }
        }
        
        /// <summary>
        /// Product copyright.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Product copyright.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YlkMZi0vq3wzKgqRan2Yh9UqMz2eLKIZb529uCcaiEHSzc9YoSzF6OmlGzFwV7SF")]
        public string Copyright {
            get {
                return ((string)(this["Copyright"]));
            }
        }
        
        /// <summary>
        /// Product license.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Product license.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YlkMZi0vq3x5r/OIwrX+b3TuIK+g9GrzrZbrskVMiAcd2h/TT+Z2rQlEZFfniu3lkkQ0dY9BdOI=")]
        public string License {
            get {
                return ((string)(this["License"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n/kJvd7Xbb8=")]
        public string Release {
            get {
                return ((string)(this["Release"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Name {
            get {
                return ((string)(this["Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FamilyName {
            get {
                return ((string)(this["FamilyName"]));
            }
        }
    }
}
