
#region License

// Copyright (c) 2013, ClearCanvas Inc.
// All rights reserved.
// http://www.clearcanvas.ca
//
// This file is part of the ClearCanvas RIS/PACS open source project.
//
// The ClearCanvas RIS/PACS open source project is free software: you can
// redistribute it and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The ClearCanvas RIS/PACS open source project is distributed in the hope that it
// will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// the ClearCanvas RIS/PACS open source project.  If not, see
// <http://www.gnu.org/licenses/>.

#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.Explorer.Dicom {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macro.ImageViewer.Explorer.Dicom.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 流水号 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingAccessionNumber {
            get {
                return ResourceManager.GetString("ColumnHeadingAccessionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingAttachments {
            get {
                return ResourceManager.GetString("ColumnHeadingAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效性 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingAvailability {
            get {
                return ResourceManager.GetString("ColumnHeadingAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出生日期 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingDateOfBirth {
            get {
                return ResourceManager.GetString("ColumnHeadingDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingDeleteOn {
            get {
                return ResourceManager.GetString("ColumnHeadingDeleteOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Name 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingFirstName {
            get {
                return ResourceManager.GetString("ColumnHeadingFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ideographic Name 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingIdeographicName {
            get {
                return ResourceManager.GetString("ColumnHeadingIdeographicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构名称 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingInstitutionName {
            get {
                return ResourceManager.GetString("ColumnHeadingInstitutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Name 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingLastName {
            get {
                return ResourceManager.GetString("ColumnHeadingLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingModality {
            get {
                return ResourceManager.GetString("ColumnHeadingModality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像数 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingNumberOfInstances {
            get {
                return ResourceManager.GetString("ColumnHeadingNumberOfInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingPatientId {
            get {
                return ResourceManager.GetString("ColumnHeadingPatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingPatientName {
            get {
                return ResourceManager.GetString("ColumnHeadingPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拼音名 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingPhoneticName {
            get {
                return ResourceManager.GetString("ColumnHeadingPhoneticName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医生 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingReferringPhysician {
            get {
                return ResourceManager.GetString("ColumnHeadingReferringPhysician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingServer {
            get {
                return ResourceManager.GetString("ColumnHeadingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM Server 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingSourceAETitle {
            get {
                return ResourceManager.GetString("ColumnHeadingSourceAETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作站名称 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingStationName {
            get {
                return ResourceManager.GetString("ColumnHeadingStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查日期 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingStudyDate {
            get {
                return ResourceManager.GetString("ColumnHeadingStudyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingStudyDescription {
            get {
                return ResourceManager.GetString("ColumnHeadingStudyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天 {0} 的本地化字符串。
        /// </summary>
        internal static string FormatDueToday {
            get {
                return ResourceManager.GetString("FormatDueToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明天 {0} 的本地化字符串。
        /// </summary>
        internal static string FormatDueTomorrow {
            get {
                return ResourceManager.GetString("FormatDueTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昨天 {0} 的本地化字符串。
        /// </summary>
        internal static string FormatDueYesterday {
            get {
                return ResourceManager.GetString("FormatDueYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (重建图像索引) {0} 的本地化字符串。
        /// </summary>
        internal static string FormatNeverSearchedReindexing {
            get {
                return ResourceManager.GetString("FormatNeverSearchedReindexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}个检查 的本地化字符串。
        /// </summary>
        internal static string FormatStudiesFound {
            get {
                return ResourceManager.GetString("FormatStudiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1}上的检查：{0}(重建图像索引) 的本地化字符串。
        /// </summary>
        internal static string FormatStudiesFoundReindexing {
            get {
                return ResourceManager.GetString("FormatStudiesFoundReindexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法查询 {0}:  {1} 的本地化字符串。
        /// </summary>
        internal static string FormatUnableToQueryServer {
            get {
                return ResourceManager.GetString("FormatUnableToQueryServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务监视器 的本地化字符串。
        /// </summary>
        internal static string LinkOpenActivityMonitor {
            get {
                return ResourceManager.GetString("LinkOpenActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除检查 的本地化字符串。
        /// </summary>
        internal static string MenuDeleteStudy {
            get {
                return ResourceManager.GetString("MenuDeleteStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string MenuOpenStudy {
            get {
                return ResourceManager.GetString("MenuOpenStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取 的本地化字符串。
        /// </summary>
        internal static string MenuRetrieveStudy {
            get {
                return ResourceManager.GetString("MenuRetrieveStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string MenuSendStudy {
            get {
                return ResourceManager.GetString("MenuSendStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开图像，服务器不具有流能力 的本地化字符串。
        /// </summary>
        internal static string MessageCannotOpenNonStreamingStudy {
            get {
                return ResourceManager.GetString("MessageCannotOpenNonStreamingStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无条件查询，会花费很长时间，你是否要继续？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmContinueOpenSearch {
            get {
                return ResourceManager.GetString("MessageConfirmContinueOpenSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你是否要删除选中的检查？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmDeleteStudies {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你是否要删除选中的检查？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmDeleteStudy {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多个服务器被选中，你是否要继续？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmSendToMultipleServers {
            get {
                return ResourceManager.GetString("MessageConfirmSendToMultipleServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除操作失败 的本地化字符串。
        /// </summary>
        internal static string MessageErrorDeletingStudies {
            get {
                return ResourceManager.GetString("MessageErrorDeletingStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取操作失败 的本地化字符串。
        /// </summary>
        internal static string MessageErrorRetrievingStudies {
            get {
                return ResourceManager.GetString("MessageErrorRetrievingStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送操作失败 的本地化字符串。
        /// </summary>
        internal static string MessageErrorSendingStudies {
            get {
                return ResourceManager.GetString("MessageErrorSendingStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开图像失败 的本地化字符串。
        /// </summary>
        internal static string MessageFailedToOpenStudy {
            get {
                return ResourceManager.GetString("MessageFailedToOpenStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将删除{0}检查任务添加到工作队列中. 的本地化字符串。
        /// </summary>
        internal static string MessageFormatDeleteStudiesScheduled {
            get {
                return ResourceManager.GetString("MessageFormatDeleteStudiesScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将删除 {0} [{1}, A#:{2}] 检查任务添加到工作队列中. 的本地化字符串。
        /// </summary>
        internal static string MessageFormatDeleteStudyScheduled {
            get {
                return ResourceManager.GetString("MessageFormatDeleteStudyScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将获取{0} 检查任务添加到工作队列中. 的本地化字符串。
        /// </summary>
        internal static string MessageFormatRetrieveStudiesScheduled {
            get {
                return ResourceManager.GetString("MessageFormatRetrieveStudiesScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将从 {3} 中获取 {0} [{1}, A#:{2}]  检查任务添加到工作队列中. 的本地化字符串。
        /// </summary>
        internal static string MessageFormatRetrieveStudyScheduled {
            get {
                return ResourceManager.GetString("MessageFormatRetrieveStudyScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将发送{0}检查任务添加到工作队列中 的本地化字符串。
        /// </summary>
        internal static string MessageFormatSendStudiesScheduled {
            get {
                return ResourceManager.GetString("MessageFormatSendStudiesScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将{1} [{2}发送到 {0}, A#:{3}] 任务添加到工作队列中. 的本地化字符串。
        /// </summary>
        internal static string MessageFormatSendStudyScheduled {
            get {
                return ResourceManager.GetString("MessageFormatSendStudyScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}无法打开图像，服务器不具有流能力 的本地化字符串。
        /// </summary>
        internal static string MessageFormatXNonStreamingStudiesCannotBeOpened {
            get {
                return ResourceManager.GetString("MessageFormatXNonStreamingStudiesCannotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始时间制定错误 的本地化字符串。
        /// </summary>
        internal static string MessageFromDateCannotBeAfterToDate {
            get {
                return ResourceManager.GetString("MessageFromDateCannotBeAfterToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病人姓名格式化无效 的本地化字符串。
        /// </summary>
        internal static string MessageInvalidPatientsName {
            get {
                return ResourceManager.GetString("MessageInvalidPatientsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开图像，服务器不具有流能力 的本地化字符串。
        /// </summary>
        internal static string MessageOneNonStreamingStudyCannotBeOpened {
            get {
                return ResourceManager.GetString("MessageOneNonStreamingStudyCannotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查正在浏览中，请关闭浏览窗口 的本地化字符串。
        /// </summary>
        internal static string MessageOneOfSelectedStudiesInUse {
            get {
                return ResourceManager.GetString("MessageOneOfSelectedStudiesInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无权查看 的本地化字符串。
        /// </summary>
        internal static string MessageOpenStudyPermissionDenied {
            get {
                return ResourceManager.GetString("MessageOpenStudyPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理 {1}中的{0}项目 ... 的本地化字符串。
        /// </summary>
        internal static string MessageProcessedItemsProgress {
            get {
                return ResourceManager.GetString("MessageProcessedItemsProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地服务器没有启动 的本地化字符串。
        /// </summary>
        internal static string MessageRetrieveDicomServerServiceNotRunning {
            get {
                return ResourceManager.GetString("MessageRetrieveDicomServerServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无权检索检查 的本地化字符串。
        /// </summary>
        internal static string MessageSearchStudyPermissionDenied {
            get {
                return ResourceManager.GetString("MessageSearchStudyPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择服务器 的本地化字符串。
        /// </summary>
        internal static string MessageSelectDestination {
            get {
                return ResourceManager.GetString("MessageSelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查正在浏览中，请关闭浏览窗口 的本地化字符串。
        /// </summary>
        internal static string MessageSelectedStudyInUse {
            get {
                return ResourceManager.GetString("MessageSelectedStudyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地服务器没有启动 的本地化字符串。
        /// </summary>
        internal static string MessageSendDicomServerServiceNotRunning {
            get {
                return ResourceManager.GetString("MessageSendDicomServerServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}检查正在浏览中，请关闭浏览窗口 的本地化字符串。
        /// </summary>
        internal static string MessageSomeOfSelectedStudiesInUse {
            get {
                return ResourceManager.GetString("MessageSomeOfSelectedStudiesInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须重新执行此操作，否则可能无法打开检查图像 的本地化字符串。
        /// </summary>
        internal static string NotificationDetailsReindexCancelled {
            get {
                return ResourceManager.GetString("NotificationDetailsReindexCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重建索引完成 的本地化字符串。
        /// </summary>
        internal static string NotificationDetailsReindexCompleted {
            get {
                return ResourceManager.GetString("NotificationDetailsReindexCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重建索引失败 的本地化字符串。
        /// </summary>
        internal static string NotificationDetailsReindexFailed {
            get {
                return ResourceManager.GetString("NotificationDetailsReindexFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重建索引正在进行中... 的本地化字符串。
        /// </summary>
        internal static string NotificationDetailsReindexRunning {
            get {
                return ResourceManager.GetString("NotificationDetailsReindexRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将重建索引任务添加到工作列表中 的本地化字符串。
        /// </summary>
        internal static string NotificationDetailsReindexScheduled {
            get {
                return ResourceManager.GetString("NotificationDetailsReindexScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消重建索引 的本地化字符串。
        /// </summary>
        internal static string NotificationReindexCancelled {
            get {
                return ResourceManager.GetString("NotificationReindexCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重建索引完成 的本地化字符串。
        /// </summary>
        internal static string NotificationReindexComplete {
            get {
                return ResourceManager.GetString("NotificationReindexComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重建索引失败 的本地化字符串。
        /// </summary>
        internal static string NotificationReindexFailed {
            get {
                return ResourceManager.GetString("NotificationReindexFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重建索引正在执行中 的本地化字符串。
        /// </summary>
        internal static string NotificationReindexRunning {
            get {
                return ResourceManager.GetString("NotificationReindexRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划任务-重建索引 的本地化字符串。
        /// </summary>
        internal static string NotificationReindexScheduled {
            get {
                return ResourceManager.GetString("NotificationReindexScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效 的本地化字符串。
        /// </summary>
        internal static string PastDue {
            get {
                return ResourceManager.GetString("PastDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM 的本地化字符串。
        /// </summary>
        internal static string PathDicom {
            get {
                return ResourceManager.GetString("PathDicom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explorer 的本地化字符串。
        /// </summary>
        internal static string PathExplorer {
            get {
                return ResourceManager.GetString("PathExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM 的本地化字符串。
        /// </summary>
        internal static string TitleDicomExplorer {
            get {
                return ResourceManager.GetString("TitleDicomExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string TitleSearch {
            get {
                return ResourceManager.GetString("TitleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询窗口 的本地化字符串。
        /// </summary>
        internal static string TitleSearchPanelPane {
            get {
                return ResourceManager.GetString("TitleSearchPanelPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送检查 的本地化字符串。
        /// </summary>
        internal static string TitleSendStudy {
            get {
                return ResourceManager.GetString("TitleSendStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器列表 的本地化字符串。
        /// </summary>
        internal static string TitleServerTreePane {
            get {
                return ResourceManager.GetString("TitleServerTreePane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览检查 的本地化字符串。
        /// </summary>
        internal static string TitleStudyBrowserPane {
            get {
                return ResourceManager.GetString("TitleStudyBrowserPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航检查 的本地化字符串。
        /// </summary>
        internal static string TitleStudyNavigatorPane {
            get {
                return ResourceManager.GetString("TitleStudyNavigatorPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除检查 的本地化字符串。
        /// </summary>
        internal static string ToolbarDeleteStudy {
            get {
                return ResourceManager.GetString("ToolbarDeleteStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string ToolbarOpenStudy {
            get {
                return ResourceManager.GetString("ToolbarOpenStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取 的本地化字符串。
        /// </summary>
        internal static string ToolbarRetrieveStudy {
            get {
                return ResourceManager.GetString("ToolbarRetrieveStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string ToolbarSendStudy {
            get {
                return ResourceManager.GetString("ToolbarSendStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除检查 的本地化字符串。
        /// </summary>
        internal static string TooltipDeleteStudy {
            get {
                return ResourceManager.GetString("TooltipDeleteStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏副本 的本地化字符串。
        /// </summary>
        internal static string TooltipHideDuplicateStudies {
            get {
                return ResourceManager.GetString("TooltipHideDuplicateStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string TooltipOpenStudy {
            get {
                return ResourceManager.GetString("TooltipOpenStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取 的本地化字符串。
        /// </summary>
        internal static string TooltipRetrieveStudy {
            get {
                return ResourceManager.GetString("TooltipRetrieveStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string TooltipSendStudy {
            get {
                return ResourceManager.GetString("TooltipSendStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示所有检查 的本地化字符串。
        /// </summary>
        internal static string TooltipShowAllStudies {
            get {
                return ResourceManager.GetString("TooltipShowAllStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含无效字符 的本地化字符串。
        /// </summary>
        internal static string ValidationInvalidCharacters {
            get {
                return ResourceManager.GetString("ValidationInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含无效字符 的本地化字符串。
        /// </summary>
        internal static string ValidationInvalidLastNameSearch {
            get {
                return ResourceManager.GetString("ValidationInvalidLastNameSearch", resourceCulture);
            }
        }
    }
}
